DROP TABLE IF EXISTS articles_tags;
DROP TABLE IF EXISTS likes;
DROP TABLE IF EXISTS articles;
DROP TABLE IF EXISTS tags;
DROP TABLE IF EXISTS comments;
DROP TABLE IF EXISTS follows;
DROP TABLE IF EXISTS users;
